JDT/Models/InvitedUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace JDT.Models
{
    public class InvitedUser
    {
        public InvitedUser()
        {
            this.DateCreated = DateTime.Now;
            this.DateModified = DateTime.Now;
            this.Hide = false;
        }
        [Required, Key, DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int InvitedUserId { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public int InvitedById { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }
        public UserProfile InvitedBy { get; set; }
        public bool? Hide { get; set; }
        
    }
}

JDT/Controllers/InvitedUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JDT.Models;
using JDT.App_Code;
using WebMatrix.WebData;
using MvcSiteMapProvider;

namespace JDT.Controllers
{
    [LocsAuthorizeAttribute]
    [SessionExpireFilterAttribute]
    [Authorize(Roles = "Administrator,ContentCreator")]
    public class InvitedUsersController : Controller
    {
        private JDTContext context = new JDTContext();

        //
        // GET: /PreConsumers/

        [MvcSiteMapNode(Title = "Friends", ParentKey = "Dashboard")]
        public ViewResult Index()
        {
           
            int uid = WebSecurity.CurrentUserId;
            return View(context.InvitedUsers.Where(pc => pc.InvitedById == uid).ToList());

        }

       
        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JDT/Views/InvitedUsers/Create.cshtml
@model JDT.Models.InvitedUser

@{
    ViewBag.Title = "Create";
}
<div class="content container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="page-title">Invite a friend<small> Remember to send the registration email on the friend list page after adding him or her.</small></h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <section class="widget">
                <header>
                    <h4>
                        <i class="fa fa-align-left"></i>
                        Add Friend
                    </h4>
                </header>
                <div class="body">
                    @using (Html.BeginForm("Create", "InvitedUsers", FormMethod.Post, new { @class = "form-horizontal", data_validate = "parsley", novalidate = "novalidate" }))
                    {
                        <fieldset>
                            <legend class="section">Invite a friend into your training community</legend>
                            <div class="row">
                                <div class="col-sm-8">
                                    @Html.Partial("_CreateOrEdit", Model)
                                </div>
                            </div>
                        </fieldset>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-danger">Submit</button>
                            <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("Index")'">Back to List</button>
                        </div>
                    }
                </div>
            </section>
        </div>
    </div>


</div>
@section scripts{
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryplugins")
    @Scripts.Render("~/bundles/backboneunderscore")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/site")
}



JDT/Views/InvitedUsers/Delete.cshtml
@model JDT.Models.InvitedUser

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>PreConsumer</legend>

    <div class="display-label">FirstName</div>
    <div class="display-field">@Model.FirstName</div>

    <div class="display-label">LastName</div>
    <div class="display-field">@Model.LastName</div>

    <div class="display-label">Email</div>
    <div class="display-field">@Model.Email</div>

    <div class="display-label">DateCreated</div>
    <div class="display-field">@String.Format("{0:g}", Model.DateCreated)</div>

    <div class="display-label">DateModified</div>
    <div class="display-field">@String.Format("{0:g}", Model.DateModified)</div>

    <div class="display-label">ContentAuthor</div>
    <div class="display-field">@(Model.InvitedBy == null ? "None" : Model.InvitedBy.LastName)</div>
</fieldset>
@using (Html.BeginForm())
{
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}
@section scripts{
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/dashboard/jqueryplugins")
    @Scripts.Render("~/bundles/backboneunderscore")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/site")
}



JDT/Views/InvitedUsers/Details.cshtml
@model JDT.Models.InvitedUser

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>PreConsumer</legend>

    <div class="display-label">FirstName</div>
    <div class="display-field">@Model.FirstName</div>

    <div class="display-label">LastName</div>
    <div class="display-field">@Model.LastName</div>

    <div class="display-label">Email</div>
    <div class="display-field">@Model.Email</div>

    <div class="display-label">DateCreated</div>
    <div class="display-field">@String.Format("{0:g}", Model.DateCreated)</div>

    <div class="display-label">DateModified</div>
    <div class="display-field">@String.Format("{0:g}", Model.DateModified)</div>

    <div class="display-label">ContentAuthor</div>
    <div class="display-field">@(Model.InvitedBy == null ? "None" : Model.InvitedBy.LastName)</div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.InvitedUserId }) |
    @Html.ActionLink("Back to List", "Index")
</p>
@section scripts{
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/dashboard/jqueryplugins")
    @Scripts.Render("~/bundles/backboneunderscore")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/site")
}


JDT/Views/InvitedUsers/Edit.cshtml
@model JDT.Models.InvitedUser

@{
    ViewBag.Title = "Edit";
}
<div class="content container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="page-title">Edit Friend<small>  Remember to send the registration email on the friend list page after adding him or her.</small></h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <section class="widget">
                <header>
                    <h4>
                        <i class="fa fa-align-left"></i>
                        Modify Friend
                    </h4>
                </header>
                <div class="body">
                    @using (Html.BeginForm("Edit", "InvitedUsers", FormMethod.Post, new { @class = "form-horizontal", data_validate = "parsley", novalidate = "novalidate" }))
                    {
                        <fieldset>
                            <legend class="section">Modify Friend</legend>
                            <div class="row">
                                <div class="col-sm-8">
                                    @Html.HiddenFor(model => model.InvitedUserId)
                                    @Html.Partial("_CreateOrEdit", Model)
                                </div>
                            </div>
                        </fieldset>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-danger">Submit</button>
                            <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("Index")'">Back to List</button>
                        </div>
                    }
                </div>
            </section>
        </div>
    </div>


</div>
@section scripts{
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryplugins")
    @Scripts.Render("~/bundles/backboneunderscore")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/site")
}

JDT/Views/InvitedUsers/Index.cshtml
@model IEnumerable<JDT.Models.InvitedUser>

@{
    ViewBag.Title = "Index";
}
<div class="content container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="page-title">Your Friends<small>View, Create, Edit from here.</small></h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">
            <section class="widget">
                <header>
                    <h4>
                        <i class="fa fa-list-alt"></i>
                        Friend List
                    </h4>
                </header>
                <div class="body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th class="hidden-xs-portrait">
                                    #
                                </th>
                                <th>
                                    First Name
                                </th>
                                <th>
                                    Last Name
                                </th>
                                <th>
                                    Email
                                </th>
                                <th class="hidden-xs">
                                    Date Created
                                </th>
                                <th>
                                    Send Registration Email
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{int x = 1;}
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="hidden-xs-portrait">
                                        @x
                                    </td>
                                    <td>
                                        @item.FirstName
                                    </td>
                                    <td>
                                        @item.LastName
                                    </td>
                                    <td>
                                        @item.Email
                                    </td>
                                    <td class="hidden-xs">
                                        @Html.DisplayFor(m => item.DateCreated)
                                    </td>
                                    <td>
                                        <button class="btn btn-sm btn-inverse" onclick="location.href = '#' ">
                                            Invite
                                        </button>
                                    </td>
                                    <td>
                                        <button class="btn btn-sm btn-primary" onclick="location.href = '@Url.Action("Edit", new {id=item.InvitedUserId})'">
                                            Edit
                                        </button>
                                        <button class="btn btn-sm btn-inverse" onclick="location.href = '@Url.Action("Details",new { id = item.InvitedUserId })'">
                                            Details
                                        </button>
                                        <button class="btn btn-sm btn-warning" onclick="location.href = '@Url.Action("Delete", new { id = item.InvitedUserId })'">
                                            Delete
                                        </button>
                                    </td>

                                </tr>
                                x += 1;
                            }
                        </tbody>
                    </table>
                    <blockquote>
                        <button class="btn btn-default btn-sm" onclick="location.href='@Url.Action("Create")'">
                            Add New
                        </button>
                    </blockquote>
                </div>
            </section>
        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/dashboard/jqueryplugins")
    @Scripts.Render("~/bundles/backboneunderscore")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/site")
}

JDT/Views/InvitedUsers/_CreateOrEdit.cshtml
@model JDT.Models.InvitedUser

@* This partial view defines form fields that will appear when creating and editing entities *@
<div class="control-group">
    @Html.LabelFor(model => model.FirstName, new { @class = "control-label" })
    <div class="controls form-group">
        @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control parsley-validated", required = "required" })
    </div>
</div>
<div class="control-group">
    @Html.LabelFor(model => model.LastName, new { @class = "control-label" })
    <div class="controls form-group">
        @Html.TextBoxFor(model => model.LastName, new { @class = "form-control parsley-validated", required = "required" })
    </div>
</div>
<div class="control-group">
    @Html.LabelFor(model => model.Email, new { @class = "control-label" })
    <div class="controls form-group">
        @Html.TextBoxFor(model => model.Email, new { @class = "form-control parsley-validated", required = "required" })
    </div>
</div>